/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppOfficerRouteImport } from './routes/_app.officer'
import { Route as AppCreateTicketRouteImport } from './routes/_app.create-ticket'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppOfficerTicketsIdRouteImport } from './routes/_app.officer.tickets.$id'
import { Route as AppAdminTicketsIdRouteImport } from './routes/_app.admin.tickets.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOfficerRoute = AppOfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateTicketRoute = AppCreateTicketRouteImport.update({
  id: '/create-ticket',
  path: '/create-ticket',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppOfficerTicketsIdRoute = AppOfficerTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => AppOfficerRoute,
} as any)
const AppAdminTicketsIdRoute = AppAdminTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/create-ticket': typeof AppCreateTicketRoute
  '/officer': typeof AppOfficerRouteWithChildren
  '/admin/tickets/$id': typeof AppAdminTicketsIdRoute
  '/officer/tickets/$id': typeof AppOfficerTicketsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/create-ticket': typeof AppCreateTicketRoute
  '/officer': typeof AppOfficerRouteWithChildren
  '/admin/tickets/$id': typeof AppAdminTicketsIdRoute
  '/officer/tickets/$id': typeof AppOfficerTicketsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/create-ticket': typeof AppCreateTicketRoute
  '/_app/officer': typeof AppOfficerRouteWithChildren
  '/_app/admin/tickets/$id': typeof AppAdminTicketsIdRoute
  '/_app/officer/tickets/$id': typeof AppOfficerTicketsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/create-ticket'
    | '/officer'
    | '/admin/tickets/$id'
    | '/officer/tickets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/create-ticket'
    | '/officer'
    | '/admin/tickets/$id'
    | '/officer/tickets/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/create-ticket'
    | '/_app/officer'
    | '/_app/admin/tickets/$id'
    | '/_app/officer/tickets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/officer': {
      id: '/_app/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof AppOfficerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-ticket': {
      id: '/_app/create-ticket'
      path: '/create-ticket'
      fullPath: '/create-ticket'
      preLoaderRoute: typeof AppCreateTicketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/officer/tickets/$id': {
      id: '/_app/officer/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/officer/tickets/$id'
      preLoaderRoute: typeof AppOfficerTicketsIdRouteImport
      parentRoute: typeof AppOfficerRoute
    }
    '/_app/admin/tickets/$id': {
      id: '/_app/admin/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/admin/tickets/$id'
      preLoaderRoute: typeof AppAdminTicketsIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminTicketsIdRoute: typeof AppAdminTicketsIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminTicketsIdRoute: AppAdminTicketsIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppOfficerRouteChildren {
  AppOfficerTicketsIdRoute: typeof AppOfficerTicketsIdRoute
}

const AppOfficerRouteChildren: AppOfficerRouteChildren = {
  AppOfficerTicketsIdRoute: AppOfficerTicketsIdRoute,
}

const AppOfficerRouteWithChildren = AppOfficerRoute._addFileChildren(
  AppOfficerRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCreateTicketRoute: typeof AppCreateTicketRoute
  AppOfficerRoute: typeof AppOfficerRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCreateTicketRoute: AppCreateTicketRoute,
  AppOfficerRoute: AppOfficerRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
